baseURL = 'https://www.simonhege.fr/'
languageCode = 'en-us'
title = 'simonhege.fr'

[params]
  description = 'Notes from a software architect'
  name= 'Simon HEGE'
  subtitle = 'Happy father of 2. Gopher. Road cyclist.'
  job = 'Software Architect'
  company = 'Amadeus'
  companyLink= 'https://amadeus.com'
  picture = 'https://avatars.githubusercontent.com/u/1748632?s=96&v=4'
  twitter = 'simonhege'
  github = 'simonhege'
  linkedin = 'simonhege'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'keywords'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 100
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'date'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 10
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'tags'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 80



[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'archetypes'
  target = 'archetypes'
[[module.mounts]]
  source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
  target = "assets/js/vendor/bootstrap.min.js"
[[module.mounts]]
  source = "node_modules/bootstrap-icons/font/fonts"
  target = "static/css/fonts"
[[module.mounts]]
  source = "node_modules/mermaid/dist/mermaid.min.js"
  target = "assets/js/vendor/mermaid.min.js"



[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
